export const states = {
states:[] = [
    {"name":"Alabama","prefix":"AL"},
    {"name":"Alaska","prefix":"AK"},
    {"name":"Arizona","prefix":"AZ"},
    {"name":"Arkansas","prefix":"AR"},
    {"name":"California","prefix":"CA"},
    {"name":"Colorado","prefix":"CO"},
    {"name":"Connecticut","prefix":"CT"},
    {"name":"Delaware","prefix":"DE"},
    {"name":"District of Columbia","prefix":"DC"},
    {"name":"Florida","prefix":"FL"},
    {"name":"Georgia","prefix":"GA"},
    {"name":"Hawaii","prefix":"HI"},
    {"name":"Idaho","prefix":"ID"},
    {"name":"Illinois","prefix":"IL"},
    {"name":"Indiana","prefix":"IN"},
    {"name":"Iowa","prefix":"IA"},
    {"name":"Kansa","prefix":"KS"},
    {"name":"Kentucky","prefix":"KY"},
    {"name":"Lousiana","prefix":"LA"},
    {"name":"Maine","prefix":"ME"},
    {"name":"Maryland","prefix":"MD"},
    {"name":"Massachusetts","prefix":"MA"},
    {"name":"Michigan","prefix":"MI"},
    {"name":"Minnesota","prefix":"MN"},
    {"name":"Mississippi","prefix":"MS"},
    {"name":"Missouri","prefix":"MO"},
    {"name":"Montana","prefix":"MT"},
    {"name":"Nebraska","prefix":"NE"},
    {"name":"Nevada","prefix":"NV"},
    {"name":"New Hampshire","prefix":"NH"},
    {"name":"New Jersey","prefix":"NJ"},
    {"name":"New Mexico","prefix":"NM"},
    {"name":"New York","prefix":"NY"},
    {"name":"North Carolina","prefix":"NC"},
    {"name":"North Dakota","prefix":"ND"},
    {"name":"Ohio","prefix":"OH"},
    {"name":"Oklahoma","prefix":"OK"},
    {"name":"Oregon","prefix":"OR"},
    {"name":"Pennsylvania","prefix":"PA"},
    {"name":"Rhode Island","prefix":"RI"},
    {"name":"South Carolina","prefix":"SC"},
    {"name":"South Dakota","prefix":"SD"},
    {"name":"Tennessee","prefix":"TN"},
    {"name":"Texas","prefix":"TX"},
    {"name":"Utah","prefix":"UT"},
    {"name":"Vermont","prefix":"VT"},
    {"name":"Virginia","prefix":"VA"},
    {"name":"Washington","prefix":"WA"},
    {"name":"West Virginia","prefix":"WV"},
    {"name":"Wisconsin","prefix":"WI"},
    {"name":"Wyoming","prefix":"WY"}
    ]
}